[tool.poetry]
name = "StanTasq"
version = "0.1.0"
description = ""
authors = ["Adam Ryczkowski <adam@statystyka.net>"]
readme = "README.adoc"

[tool.poetry.dependencies]
python = "^3.12"
taskiq = { version = "^0.11.10", optional = false, extras = ["reload"] }
taskiq-redis = "^1.0.2"
loguru = "^0.7.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

#[tool.poetry.scripts]
#run-server = "mikapi:app.run"
